### ISSUE TITLE
print on what line the xml is not valid

### ISSUE THREAD

**Issue by onyxde** [amouat/xsd-validator#11]
If the xml is not valid, no line number is printed. 
This can easily solved by adding ex.getLineNumber() and ex.getColumnNumber()
This helps to find the error in the xml file.
I have a patch created.

Regards

PS: I do not know how to make this patch available to you. I have a local branch.
Here is the patch:
```
diff --git a/src/xsdvalidator/validate.java b/src/xsdvalidator/validate.java
index 346c884..4839999 100644
--- a/src/xsdvalidator/validate.java
+++ b/src/xsdvalidator/validate.java
@@ -65,6 +65,9 @@ public class validate {
             }
             catch (SAXParseException ex) {
                 System.out.println(mXMLFileName + " fails to validate because: \n");
+                               System.out.println( "column number "+ex.getColumnNumber());
+                               System.out.println( "line number "+ex.getLineNumber());
+
                 System.out.println(ex.toString());
                 System.out.println();
             }
```

**Comment by amouat** [comment]
Thanks, good idea.

**Comment by onyxde** [comment]
I opened a pull request. Please merge changes if appropriate.

**Comment by amouat** [comment]
Unfortunately, this seems to be dependent on Java 8 and I don't want to tie the project to Java 8.

However, because of other issues, I might start bundling a Xerces jar rather than using the Java version, in which case I could make this change. For that reason, I'll leave this issue open, but I'm going to close the pull request.

**Comment by onyxde** [comment]
I am running it on java 1.7.0_71.
It depends on SAXParser -> SAXParseException from Version 1.0 to 2.0.1 (and later)
The other issues I do not know.

**Comment by amouat** [comment]
Ok, let me take another look. I don't think there's a problem with Java 7, as it's 4 years old now. It might still make more sense to ship with an XML library.

**Comment by amouat** [comment]
Finally merged this. Apologies for taking so long.
